### ISSUE TITLE
Changing indentation settings is not effective

### ISSUE THREAD

**Issue by ljazgar** [arturbosch/detekt#1039]
## Expected Behavior
When indentSize and continuationIndentSize are set to value other than 4 it should take it into consideration.

## Current Behavior
When I set indentSize and continuationIndentSize to 2, detekt-formatting still expects 4-space indentation. 

## Steps to Reproduce (for bugs)
1. Change indentation: indentSize and continuationIndentSize to 2 in default-detekt-config.yml
```
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
    continuationIndentSize: 2
```
2. Write code with 2-space indentation.
3. Run gradle detektCheck
4. Detekt reports error
```
Ruleset: formatting - ...
	Indentation - [PsiWhiteSpace] at ... 
```

## Context
It's not possible to change default indentation.

## Your Environment
* Version used: 1.0.0.RC8
* Operating System and version: Mac OS
