### ISSUE TITLE
MaxLineLength should allow excluding import and package statements

### ISSUE THREAD

**Issue by xMickeymikex** [arturbosch/detekt#111]
Hey,

Another issue i found is MaxLineLength, which is not working, i changed it to 15 just to see the results, and build has succeed with no warns or errors.

detekt.yml part:

```

style:
  active: true
  WildcardImport:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 15
  NamingConventionViolation:
    active: true
    variablePattern: '^(_)?[a-z$][a-zA-Z$0-9]*$'
    constantPattern: '^([A-Z_]*|serialVersionUID)$'
    methodPattern: "^[`]?[a-z$'][a-zA-Z$0-9]*[`]?$"
    classPattern: '[A-Z$][a-zA-Z$]*'
    enumEntryPattern: '^[A-Z$][a-zA-Z_$]*$'


```
