### ISSUE TITLE
ObjectPropertyNaming/privatePropertyPattern not loaded from configuration

### ISSUE THREAD

**Issue by Tolriq** [arturbosch/detekt#1122]
```
  ObjectPropertyNaming:
    active: true
    privatePropertyPattern: '*'
```

Will still triggers errors with message when they do not match the default pattern:
ObjectPropertyNaming -> Private object property names should match the pattern: (_)?[A-Za-z][A-Za-z0-9]*

## Your Environment

* Version used: RC9

**Comment by Tolriq** [comment]
The first try was to just add an _ and duplicate the public one ;)

Same result.

**Comment by rock3r** [comment]
I cannot reproduce the issue; I tried adding a test for `ObjectPropertyNaming` passing a config with `privatePropertyPattern: '.*'` and it doesn't detect any private properties on an `Object` with any weird naming. Seems to be working fine for me. What's your specific case?

**Comment by rock3r** [comment]
See the PR linked above for the specific test added.

**Comment by Mauin** [comment]
I just noticed that in your configuration you define `propertyPattern` twice. Does removing one of those lines solve the issue?

**Comment by Tolriq** [comment]
Nope fixed to:
```
  ObjectPropertyNaming:
    active: true
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '(_)?[A-Za-z][_A-Za-z0-9]*'
```

And still the issue.
(Duplicate was caused by diff error when updating the conf to new generated config and I did not pay attention enough)

For test completion it's the same with

```
  ObjectPropertyNaming:
    active: true
    privatePropertyPattern: '(_)?[A-Za-z][_A-Za-z0-9]*'
```
