### ISSUE TITLE
Architecture Compliance Rule

### ISSUE THREAD

**Issue by deeprim** [arturbosch/detekt#1164]
Introduce new rule that will allow the one to prohibit usage of classes from a certain package in classes of an arbitrary package:

```yml
architecture-compliance:
  prohibit:
    in: 
      - 'com.mypackage.*'
      - 'com.myotherpackage.*'
    from:
      - 'org.unwantedpackage.*'
    message:
      - 'Classes from `org.unwantedpackage.*` are disallowed for usage within `com.mypackage`...'
    # the next is questionable, why we would reduce severity for prohibited class?
    severity: 'error'
```

The similar rule may be found in sonar rules: [Architecture Rule Engine](https://docs.sonarqube.org/display/SONARQUBE44/Architecture+Rule+Engine)

The rule will allow developers to ensure that for an example "web" tier won't sprawl into "service" tier (or "repository" tier)
