### ISSUE TITLE
Build upon the default configuration

### ISSUE THREAD

**Issue by PaulWoitaschek** [arturbosch/detekt#1248]
When I supply an empty configuration file, the defaults are being run.

Now I want to suppress the `MagicNumber` rule:

```
style:
  MagicNumber:
    active: false
```

It seems that detekt now runs nothing at all. Is it possible to use detekt so it only disables this one but keeps all the other defaults?
I trust in this library to provide good defaults and only want to suppress some, without copy-pasting a 500-line configuration and updating each time you change your recommendations / add rules.

**Comment by arturbosch** [comment]
Thats actually a valid point and I would expect the same.
I will look into this.

**Comment by passsy** [comment]
I ran into the same problem. Not good documented but it already works. Try this:

```yaml
# Enable all rules by default
failFast: true

# Configure rules and override default values
style:
  MagicNumber:
    active: false
```
