### ISSUE TITLE
Add options to Kotlin DSL to configure console output

### ISSUE THREAD

**Issue by binkley** [arturbosch/detekt#1419]
Again, apologies if I missed this in the documentation.  I went through the Kotlin DSL docs, and the yaml file configuration, and looked into the `DetektExtension` class and it's friends and relations.

I didn't spot how to configure stdout/console output with Kotlin DSL.  For example, with yaml, I spot:
https://arturbosch.github.io/detekt/configurations.html#console-and-output-reports
```
console-reports:
  active: true
  exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'BuildFailureReport'

output-reports:
  active: true
  exclude:
  #  - 'HtmlOutputReport'
  #  - 'TxtOutputReport'
  #  - 'XmlOutputReport'
```
I looked for something similar with Kotlin, and found that I can configure HTML and XML report files, but I didn't see the DSL supporting configuration of console output.  I was hoping for something under `reports`:
```
	val reports = DetektReports(project)
	fun reports(configure: Action<DetektReports>) = configure.execute(reports)
```
And:
```
class DetektReports(project: Project) {

	val xml = DetektReport(XML, project)

	val html = DetektReport(HTML, project)

	fun xml(configure: DetektReport.() -> Unit) = xml.configure()
	fun xml(closure: Closure<*>): DetektReport = ConfigureUtil.configure(closure, xml)

	fun html(configure: DetektReport.() -> Unit) = html.configure()
	fun html(closure: Closure<*>): DetektReport = ConfigureUtil.configure(closure, html)
}
```
