### ISSUE TITLE
Running formatting checks without formatting the code on CI

### ISSUE THREAD

**Issue by PavelSynek** [arturbosch/detekt#159]
We would like to run detekt on our CI with all checks, including formatting. The problem is that we don't want to actually reformat code on CI, just fail the build if there are any errors. But if we run `detektFormat` with `autoCorrect: false`, it prints format errors, but doesn't fail the build.

Is it possible to either add formatting checks to `detektCheck` or make `detektFormat` fail the build (possibly enabled by some flag) if there are any formatting errors?

**Comment by arturbosch** [comment]
So you already running `detektFormat` on CI and it does not format code (like you want it?), but formatting should also fail the build?

How do your build settings look like ? I turned off formatting weights in the build setting, try turning it on

```yml
build:
  warningThreshold: 5
  failThreshold: 10
  weights:
    complexity: 2
    formatting: 0
    LongParameterList: 1
    comments: 0.5
```

**Comment by PavelSynek** [comment]
This is our current detekt.yml

```yml
autoCorrect: false

build:
  warningThreshold: 1
  failThreshold: 1

potential-bugs:
  active: true
  LateinitUsage:
    active: false

exceptions:
  active: true

empty-blocks:
  active: true

complexity:
  active: true

code-smell:
  active: true

formatting:
  active: true
  useTabs: true

style:
  active: true

comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
```

We simply want a way to fail the build if the code isn't formatted properly. We've tried increasing weight for `formatting`, but weights apply only for `detektCheck` task which doesn't run `formatting`.
