### ISSUE TITLE
Add support for suppressing non-error output

### ISSUE THREAD

**Issue by gavingolden** [arturbosch/detekt#1619]
## Expected Behavior
A Gradle/Maven configuration option can be used to disable non-failure log output

## Current Behavior
The validation report is always printed.

## Context
When running `gradle build` nearly the entire output is detekt-related. I'd like to only see output when validation fails.

**Comment by arturbosch** [comment]
Hey thanks for the feedback.
Can you try turning off all console output with:
```
console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
  #  - 'BuildFailureReport'
```
inside the config file?

These lines are already in your config, you need just to remove the `#`.
