### ISSUE TITLE
AutoCorrect: NewLineAtEndOfFile / FinalNewline / NoWildcardImports

### ISSUE THREAD

**Issue by jonas-arkulpa** [arturbosch/detekt#1746]
I'm currently struggling with the auto correct feature.
I got it working to the point that it auto corrects some issues.
But it never adds final new lines or corrects the wildcard issues.
Regarding the new lines I also tried to add an [editorconfig for ktlint](https://github.com/pinterest/ktlint#editorconfig), but it haven't helped either.
Can you point me into the right direction?

Top-level build.gradle:
```
plugins {
    id("io.gitlab.arturbosch.detekt").version("1.0.0-RC15")
}

dependencies {
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.0.0-RC15")
}

tasks.withType(io.gitlab.arturbosch.detekt.Detekt) {
    // ...
    autoCorrect = true
}

detekt {
    input = files(rootProject.rootDir)
    config = files("$rootDir/detekt-config.yml")
    parallel = true
    ignoreFailures = false
}
```

detekt-config.yml:
```
formatting:
  active: true
  android: true
  autoCorrect: true
  FinalNewline:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
    autoCorrect: true
style:
  active: true
  NewLineAtEndOfFile:
    active: true
```
