### ISSUE TITLE
exclude-rules stopped working in RC15

### ISSUE THREAD

**Issue by TWiStErRob** [arturbosch/detekt#1806]
```yaml
test-pattern: # Configure exclusions for test sources
  active: true
  patterns: # Test file regexes (make sure they're platform independent)
    - '.*[/\\]test[/\\].*'
    - '.*Test.kt'
  exclude-rules:
    - 'UnusedImports'

style:
  active: true
  UnusedImports:
    active: true
```
means that we want to check `UnusedImports` everywhere, except in test code. Test code resides in `**/test/**` folder or a file named `*Test.kt`. This was working up to and including RC14.

## Expected Behavior
```
Ruleset: style - 10min debt
        UnusedImports - [Main.kt] at exclude-rules-ignored\src\main\kotlin\pack\age\Main.kt:3:1
```

## Observed Behavior
```
Ruleset: style - 10min debt
        UnusedImports - [Main.kt] at exclude-rules-ignored\src\main\kotlin\pack\age\Main.kt:3:1
        UnusedImports - [MainTest.kt] at exclude-rules-ignored\src\test\kotlin\pack\age\MainTest.kt:3:1
```

## Steps to Reproduce
1. Clone https://github.com/TWiStErRob/repros repo
1. `cd detekt\exclude-rules-ignored`
1. `cls && gradlew clean detekt --console=plain --no-build-cache`

## Context
Can't update Gradle plugin from RC14 to RC16 because it starts to give a ton of false positives. Also people who have updated to the latest IntelliJ IDEA plugin are now seeing all-red test files, because detekt is checking rules which we don't want in test code.

## Your Environment

* Version of detekt used: RC16
* Version of Gradle used (if applicable): 5.5.1
* Operating System and version: Windows 10 x64
* Link to your project (if it's a public repository): https://github.com/TWiStErRob/repros/tree/master/detekt/exclude-rules-ignored
