### ISSUE TITLE
LateinitUsage: exclude Spring annotations in default config?

### ISSUE THREAD

**Issue by bagage** [arturbosch/detekt#1837]
In spring, `@Autowired` annotation is used on `lateinit var`:

```kt
@Autowired
lateinit var userRepository: UserRepository
```

Detekt yields that it is a wrong `LateinitUsage`, and we have to add in detekt-config.yml:

```yml
potential-bugs:
  LateinitUsage:
    excludeAnnotatedProperties: "org.springframework.beans.factory.annotation.*"
```

What about making that the default in `default-detekt-config.yml`?
