### ISSUE TITLE
New Rule: ForbiddenMethod

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#1933]
ForbiddenMethod

## Expected Behavior of the rule
This new rule will allow you to add methods that are forbidden.

Kotlin provides you `@Deprecated` to force you to use another method. And this annotation should be prefered over ForbiddenMethod but if you are using an external libraries you can't deprecate those methods.

The idea is to use something similar than forbidden imports BUT for methods. The configuration would be something like:

```yml
  ForbiddenMethod:
    active: true
    methods: 'com.bumptech.glide.Glide.with(Context), com.bumptech.glide.Glide.with(Activity), io.reactivex.disposables.CompositeDisposable.dispose()'
```

## Context
In out team we are changing or way of work. Some of these changes are like: "from now on, we are not going to use the method XXX". The last one was: from now on we are going to inject the Glide `RequestManager` so call `Glide.with(XXX)` is forbidden.

I know that I can create my custom rules but I think that this rule is generic enought to be added in the project. It's exactly the same as `ForbiddenImport` but when you don't want to forbid all the class, just some methods.
