### ISSUE TITLE
excludedFunctions in MagicNumber not working?

### ISSUE THREAD

**Issue by pasniak** [arturbosch/detekt#1936]
Does the following rule should stop reporting magic numbers for functions such as `dip(4)`, `padLeft(4f)` ?  It does not seem to work....

```
  MagicNumber:
    active: true
    excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt,**/unused/**,**/*Data.kt"
    excludedFunctions: "pad**,dip**" 
```
