### ISSUE TITLE
NoWildcardImports excludeImports

### ISSUE THREAD

**Issue by jonas-arkulpa** [arturbosch/detekt#1940]
As the conversation on the related issue https://github.com/arturbosch/detekt/issues/1468 is locked I arrogate to create a new one. 😉 

We currently have the same issue with `java.util.*` imports.

I understand the difference between `WildcardImport` and `NoWildcardImports` (ktlint).

With the workaround described in https://github.com/arturbosch/detekt/issues/1468#issuecomment-476390151 I would loose the autoCorrect feature.

Is it possible to workaround this limitation?

## Expected Behavior
Excludes and auto corrections can be used simultaniously.

## Observed Behavior
These ktlint and detekt features can't be properly combined.

![NoWildcardImportsErrorExample](https://user-images.githubusercontent.com/17269256/65317263-cc915080-db9b-11e9-96d6-a825184799fc.png)

## Steps to Reproduce
```yaml
formatting:
  active: true
  android: true
  autoCorrect: true
  NoWildcardImports:
    active: true
    autoCorrect: true

style:
  active: true
  WildcardImport:
    active: true
    excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
    excludeImports: 'java.util.*,kotlinx.android.synthetic.*'
```
