### ISSUE TITLE
Forbid internal package usage by default

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#1970]
Usually in the libraries there is an `internal` package that should not be used by the users. This is kind of a common pattern. For this reason I think that set `*.internal.*` as a default value for `ForbiddenImport` have a lot of sense. No one should be using anything that it's inside of those package.

I find a problem with this. If you are a library mantainer you can have this package and you are allowed to use your own internal package. I'm not a maintainer of any library, but probably for them this is not a big deal. I think that they prefer that the users don't use their internals and then complain for breaking changes.

If we want to find a good solution for them maybe a whitelist could work. Something like:
```yml
  ForbiddenImport:
    imports: '*.internal.*
    whitelist: 'my.cool.library.internal.*'
```
