### ISSUE TITLE
LimitPropertyVisibilityRule that allows to specify visibility of properties via meta information

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#208]
I have this crazy idea that I'd like to constraint certain properties to a specific visibility modifier since in Kotlin everything is public by default.

For now flagging the following code

```
@BindView(R2.id.activityAboutToolbar) lateinit var toolbar: Toolbar
```

would be enough, since I want the property to be internal.

I think that as a first step declaring the annotations is enough so something like:

```yaml
LimitPropertyVisibilityRule:
  1:
    package: "butterknife.*"
    visibilityModifier: "internal"
```

What do you guys think?
