### ISSUE TITLE
Unexpected nested config for 'build>weights'.

### ISSUE THREAD

**Issue by 1951FDG** [arturbosch/detekt#2128]
## Steps to Reproduce
Unexpected nested config for 'build>weights'.
```
build:
  maxIssues: 10
  weights:
     complexity: 2
```

## Workaround
If I comment it out, then no issue occurs
```
build:
  maxIssues: 10
  weights:
    # complexity: 2
```

## Context
I can't specify custom weights anymore as of version 1.2.0, this worked on Version 1.1.1 

## Your Environment
* Version of Detekt used: 1.2.0
* Version of Gradle used (if applicable): 5.4.1
* Operating System and version: macOS 10.13.6

**Comment by arturbosch** [comment]
Thanks for reporting this. This is a serious regression we need a bugfix release for.

**Comment by 1951FDG** [comment]
Np, thanks for looking into it.

**Comment by arturbosch** [comment]
For now you could use:

```yaml
config:
  validation: false
  # or
  excludes: build>weights>.*
```

to skip validation at all or for this properties.
