### ISSUE TITLE
Run custom rules on Android

### ISSUE THREAD

**Issue by robertpicsart** [arturbosch/detekt#2285]
Hi. I am trying to run my custom rules on Android project, but it seems not working.

Here is my project build.gradle file
```
buildscript {
    ext.kotlin_version = '1.3.61'
    repositories {
        mavenCentral()
        jcenter()
        google()
        maven { url "https://plugins.gradle.org/m2/" }
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.4.0"
    }
}

allprojects {
    repositories {
        mavenCentral()
        jcenter()
        google()
        maven { url "https://plugins.gradle.org/m2/" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Here is the app level build.gradle file
```
...
dependencies {
    ...
    implementation "io.gitlab.arturbosch.detekt:detekt-api:1.4.0"
}

apply plugin: 'io.gitlab.arturbosch.detekt'

detekt {
    toolVersion = "1.4.0"
//    buildUponDefaultConfig = true
    input = files("src/main/java/demo/detekt")
    config = files("$rootDir/custom-config.yml")
    reports {
        xml { enabled = false }
        html {
            enabled = true
            destination = file("build/reports/detekt.html")
        }
        txt { enabled = false }
    }
//    ruleSets = "$rootDir/app/libs/detekt-rules-1.4.0.jar"
}

dependencies {
    detekt "io.gitlab.arturbosch.detekt:detekt-api:1.4.0"
    detekt "io.gitlab.arturbosch.detekt:detekt-cli:1.4.0"
    detekt "io.gitlab.arturbosch.detekt:detekt-rules:1.4.0"
    detektPlugins(project(path: ':detekt-rules-1.4.0'))
}
```

My custom config is:
```
config:
  validation: true
  # 1. exclude rule set 'sample' and all its nested members
  # 2. exclude every property in every rule under the rule set 'sample'
  excludes: "test.*,test>.*>.*"
test:
  TooManyFunctions:
    active: false
```

My custom rule provider is:
```
class CustomRulesProvider : RuleSetProvider {
    override val ruleSetId: String = "test"

    override fun instance(config: Config): RuleSet {
        return RuleSet(
            ruleSetId, listOf(
                TooManyFunctions()
            )
        )
    }
}
```

TooManyFunctions() I took from your example.
