### ISSUE TITLE
Use yml arrays to list the ForbiddenImports

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2463]
This is right now my config for `ForbiddenImports`

```yml
  ForbiddenImport:
    active: true
    imports: 'kotlinx.android.synthetic.*,butterknife.*,org.mockito.*,java.util.List,java.util.Arrays,java.util.HashSet,java.util.Set,java.util.Map,java.util.HashMap,java.util.ArrayList,java.util.Collections.emptyList,java.util.Collections.singletonList,coches.net.core.extensions.bindView,coches.net.core.extensions.bindOptionalView,com.adevinta.android.extensions.view.bindView,com.adevinta.android.extensions.activity.bindView,com.adevinta.android.extensions.recycler.bindView,com.adevinta.android.extensions.fragment.bindView'
```

It's really difficult to manage and to review.

It would be great to allow this:

```yml
  ForbiddenImport:
    active: true
    imports:
    - 'kotlinx.android.synthetic.*'
    - 'butterknife.*'
    - 'org.mockito.*'
    - 'java.util.List'
    - 'java.util.Arrays'
    - 'java.util.HashSet'
    - 'java.util.Set'
    - 'java.util.Map'
    - 'java.util.HashMap'
    - 'java.util.ArrayList'
    - 'java.util.Collections.emptyList'
    - 'java.util.Collections.singletonList'
    - 'coches.net.core.extensions.bindView'
    - 'coches.net.core.extensions.bindOptionalView'
    - 'com.adevinta.android.extensions.view.bindView'
    - 'com.adevinta.android.extensions.activity.bindView'
    - 'com.adevinta.android.extensions.recycler.bindView'
    - 'com.adevinta.android.extensions.fragment.bindView'
```

What do you think? I'm sure that we can use this in other rules too.

*Side Note: reformating the list of imports I just spoted a problem in it. It was impossible to spot it in the long list.*
