### ISSUE TITLE
Rule configuration request: Ignore based on annotations

### ISSUE THREAD

**Issue by ZacSweers** [arturbosch/detekt#2563]
## Expected Behavior of the rule
```yml
LongParameterList:
  active: true
  functionThreshold: 7
  constructorThreshold: 7
  ignoreDefaultParameters: false
  ignoreDataClasses: true
  ignoreAnnotated: "javax.inject.Inject,javax.annotation.Generated"
```

## Context
Currently the `LongParameterList` rule applies to all constructors but has an opt-out for data classes. I'd like to suggest adding a new configuration to ignore based on annotations, such as `javax.inject.Inject`. This comes up often in our DI plumbing
