### ISSUE TITLE
TooManyFunctionsRule

### ISSUE THREAD

**Issue by xMickeymikex** [arturbosch/detekt#265]
TooManyFunctionsRule report does not take the value from .yml file 
```
autoCorrect: true
build:
  warningThreshold: 1
  failThreshold: 1
  weights:
    complexity: 1
    formatting: 0
    LongParameterList: 1
    comments: 1
complexity:
  active: true
  TooManyFunctions:
    threshold: 23
...
```
Class with 24 functions failed the build and returned the output:

```
Only new findings are printed as baseline.xml is found:
Ruleset: code-smell
Ruleset: complexity
	TooManyFunctions - 24/10 - [MainActivity.kt] at  .../MainActivity.kt:1:1
Ruleset: empty-blocks
Ruleset: exceptions
Ruleset: formatting
Ruleset: potential-bugs
Ruleset: style
```
