### ISSUE TITLE
Rule NoDocOverPublicMethod works on public methods from internal classes

### ISSUE THREAD

**Issue by emcegp** [arturbosch/detekt#266]
Is this planned behaviour? I think public methods from internal classes should be excluded from this rule. The same for internal classes themselves...

**Comment by arturbosch** [comment]
Could you check this behaviour in a newer version? `NoDocOverPublicMethod` is now `UndocumentedFunction` etc, thank you!

**Comment by emcegp** [comment]
I have something like this:
```internal interface HeaderContract {

    interface View {
        fun showLogo()
        fun hideLogo()
        fun showLogin()
        fun hideLogin()
        fun showJoin()
        fun hideJoin()
    }

    interface Presenter {
        fun didTapSearch(headerState: HeaderState)
    }
}```
and still getting: `UndocumentedPublicClass` and `UndocumentedPublicFunction`

**Comment by arturbosch** [comment]
How Kotlin handles the visibility of inner interfaces when the outer class is internal? Can you still use the interfaces from outside the package? If no then it is a detekt bug.

This is the new configurations for comments:
```
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false
``` 

If you turn off searchInInnerClass, the documentation check would not appear.
