### ISSUE TITLE
Get warning when rule is not defined

### ISSUE THREAD

**Issue by carlospinho04** [arturbosch/detekt#407]
I have the following configuration file:
````
autoCorrect: false
failFast: false

potential-bugs:
  active: false

performance:
  active: false

exceptions:
  active: false

empty-blocks:
  active: false

complexity:
  active: false

code-smell:
  active: false

formatting:
  active: false

style:
  active: true
  MagicNumber:
    active: true

comments:
  active: false

```
and this code:
```
fun main(args : Array<String>) {
    val myFloat = 5.0
  println("Hello, world!")
}
`
``
and i'm receiving "NewLineAtEndOfFile" and "MagicNumber" warnings.
I only have "MagicNumber" rule active, and i'm receiving "NewLineAtEndOfFile" warning too.
