### ISSUE TITLE
Omit gradle task output

### ISSUE THREAD

**Issue by MaximYesman** [arturbosch/detekt#448]
Hello!

I configure gradle task in my project as described here https://github.com/arturbosch/detekt#gradle , and add it build.
Is it possible to omit logs some how?
For example: leave only total weight

Thank you!

**Comment by arturbosch** [comment]
You can exclude some parts of the console report in the config:

```
console-reports:
  active: true
  exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'BuildFailureReport'
```
