### ISSUE TITLE
Config file paths should be recognized cross-platform

### ISSUE THREAD

**Issue by sewerk** [arturbosch/detekt#637]
Detekt check should be able to recognize correct path to ignore from config file, when using of different operating systems.
Config file was created for unix:
```
test-pattern:
  active: true
  patterns:
    - '.*/test/.*'
    - '.*/androidTest/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
```
But when run on Windows its reporting syntax errors for paths like `app\src\test\....`
How to configure detekt so it can be used across team with different OSs?
