### ISSUE TITLE
Consider adding ignoreOptionalParameters to LongParameterList

### ISSUE THREAD

**Issue by serj-lotutovici** [arturbosch/detekt#673]
I stumbled across a situation when I would like to keep the threshold for LongParameterList small, with the exception if a parameter has a default value.

In the yaml config this would look like this:
```yaml
complexity:
  LongParameterList:
    ignoreOptionalParameters: true
```

What are your thoughts? Would you accept a PR with this addition?
