### ISSUE TITLE
Add class name exclusion or pattern exclusion for VariableNaming rule

### ISSUE THREAD

**Issue by emartynov** [arturbosch/detekt#764]
I work with API that returns couple of jsons like:
```{"_self":"url"}``` or ```{"_links":"url"}```

I have written DTO to handle parsing and you can guess that variable names there are following JSON.
It would be great to exclude classes with patter `*DTO` or maybe specific variable names.

**Comment by arturbosch** [comment]
Maybe we should think about an option to exclude rules for given patterns like we do with `test-pattern`?
Something like:
```yaml
exclusion-patterns:
  exclusions-pattern:
    pattern: .*DTO.kt
    rules:
      - VariableNaming
      - FunctionNaming
```
What dow you think @schalkms @Mauin ?
