### ISSUE TITLE
Exclusion patterns in detekt-config

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#775]
As mentioned in #764 there should be an option to exclude rules for given patterns.
For instance:
```yaml
exclusion-patterns:
  exclusion-pattern:
    pattern: .*DTO.kt
    rules:
      - VariableNaming
      - FunctionNaming
```
After this feature is implemented the config option `excludeClassPattern` in `VariableNaming` and `FunctionNaming` should be removed.

**Comment by schalkms** [comment]
This is already implemented.

```Yaml
TooManyFunctions:
  active: true
  excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"
```
