### ISSUE TITLE
VariableNaming not working after 1.0.0.RC5-6

### ISSUE THREAD

**Issue by filipemp** [arturbosch/detekt#905]
## Expected Behavior
When running detekt I expect it shows something on the report regarding style/VariableNaming 

## Current Behavior
The check runs successfully after the `1.0.0.RC5-6`

## Steps to Reproduce (for bugs)
Configure the `detekt.yml` file to this:
```
VariableNaming:
    active: true
    variablePattern: '(?![ms]{1}[A-Z]{1})[A-Za-z0-9]*'
    privateVariablePattern: '(_)?(?![ms]{1}[A-Z]{1})[A-Za-z0-9]*'
```
run `./gradlew detektCheck` with any release after `1.0.0.RC5-6`
You can set 
```
build:
    warningThreshold: 1
    failThreshold: 1
```
or 
```
build:
    maxIssues: 1
```

Then have a kotlin file as such
```
class MyKotlinFile {
    val mBlah = true
}
```

## Context
My goal is to make the check fail If I have something declared in hungarian notation style

## Your Environment
* Version used: 1.0.0-RC6 to 1.0.0-RC7
* Operating System and version: macOS 10.13.4
