### ISSUE TITLE
[Poll] Do people care about separated EmptyXXXBlock, ThrowXXX and CatchXXX rules?

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#95]
Now every case has it's own rule - example `EmptyFunctionBlock` or `ThrowRuntimeException`. As each rule visits a whole kotlin file, there is kind of an overhead when ~10 nearly the same rules visit this file.

I favored the above approach in the beginning of detekt because it allowed `out-of-the-box-yaml-configuration` for each of this rules.

To remove this overhead, there are two options + leaving as it is is option three. Please thumps up or down to vote on the options.

**Comment by arturbosch** [comment]
Option 1: Leave as it is now, configuration of the rules stays the same:

```yaml

exceptions:
  active: true
  CatchNullpointerException:
    active: false
  CatchIndexOutOfBoundsException:
    active: true
  ...

empty-blocks:
  active: true
  EmptyFunctionBlock:
    active: false
  EmptyClassBlock:
    active: true
  ...
```

**Comment by arturbosch** [comment]
Option 2: Create super rule which handles all flavours of EmptyXXX, CatchXXx or ThrowXXX

```yaml
style:
  ...
  EmptyBlock:
    active: true/false
  ...
potential-bugs:
  ...
  CatchIndexOutOfBoundsException:
    active: true/false
  ...
```

**Comment by arturbosch** [comment]
Option 3: Like option 2 but with configurable flavours

```yaml
style:
  ...
  EmptyBlock:
    active: true/false
    EmptyFunctionBlock:
      active: true/false
    EmptyCatchBlock:
      active: true/false
  ...
potential-bugs:
  ...
  TooGeneralExceptionIsThrown:
    active: true/false
    ThrowRuntimeException:
      active: true/false
    ...
  ...
```
